export const GET_CURRENCY_USD = 'GET_CURRENCY_USD';
export const GET_CURRENCY_EUR = 'GET_CURRENCY_EUR';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const SET_CURRENCY_SIGN = 'SET_CURRENCY_SIGN';
export const CLEAR_CURRENCY_SIGN = 'CLEAR_CURRENCY_SIGN';
