export const CURRENCY_CONVERTER_API_URI = process.env.REACT_APP_CURRENCY_CONVERTER_API_URI;
export const CURRENCY_CONVERTER_API_KEY = process.env.REACT_APP_CURRENCY_CONVERTER_API_KEY;
export const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN;
